<?php

namespace block_ai_assistant;

defined('MOODLE_INTERNAL') || die();

global $CFG;
require_once($CFG->libdir . '/pdflib.php');

/**
 * TCPDF subclass used by {@see gradebook_export::render_pdf()}.
 *
 * Exists so we can (a) override the default "Powered by TCPDF" footer that
 * Moodle's \pdf inherits from upstream, and (b) print a lightweight
 * "{course}   {n} / {total}   Generated by Cria" footer instead.
 */
class gradebook_pdf extends \pdf
{
    /** @var string Text shown on the footer's left side (usually the course short name). */
    protected $footer_left = '';

    /** @var string Text shown on the footer's right side (usually our product tag line). */
    protected $footer_right = '';

    public function __construct(string $footer_left = '', string $footer_right = '')
    {
        parent::__construct();
        $this->footer_left = $footer_left;
        $this->footer_right = $footer_right;
    }

    /**
     * Replace the default TCPDF footer.
     */
    public function Footer()
    {
        $this->SetY(-12);
        $this->SetFont('helvetica', '', 8);
        $this->SetTextColor(120, 120, 120);

        $w = $this->getPageWidth() - $this->original_lMargin - $this->original_rMargin;
        $col = $w / 3;

        $page_txt = $this->getAliasNumPage() . ' / ' . $this->getAliasNbPages();

        $this->Cell($col, 6, $this->footer_left, 0, 0, 'L', false, '', 1);
        $this->Cell($col, 6, $page_txt, 0, 0, 'C', false, '', 1);
        $this->Cell($col, 6, $this->footer_right, 0, 0, 'R', false, '', 1);
    }
}
